### ISSUE TITLE
Having 127.0.0.1 and port 8001 hardcoded in the frontend code makes separating services hard

### ISSUE THREAD

**Issue by kuyper** [foxmask/joplin-web#11]
Example: in joplin-front/src/modules/notes/api.js there are calls like

`axios.get('http://127.0.0.1:8001/api/jw/notes/') `

I am experimenting around putting the backend and frontend into separate docker containers which won't easily work if I cannot reference another address

**Comment by foxmask** [comment]
I could fix that with [vue.config.js](https://cli.vuejs.org/config/#devserver-proxy)
