### ISSUE TITLE
No module named 'joplin_web.views'

### ISSUE THREAD

**Issue by willowj** [foxmask/joplin-web#12]
conda env python3.6 , win10:
`python manage.py migrate`

    joplin-web\joplin_web\urls.py", line 20, in <module>
    from joplin_web.views import base
    ModuleNotFoundError: No module named 'joplin_web.views'

there is no "views.py" in joplin_web.

 Is i missed something?

Besides,  missed "django-debug-toolbar"  in requirements.txt: `not found debug-toolbar`

**Comment by foxmask** [comment]
i've added views.py 
for the debug toolbar by default the settings set DEBUG to true so we need to pip install -r requirements-dev.txt, otherwise set DEBUG to false and no need to install it.

**Comment by willowj** [comment]
thanks for reply and this repository.
It will be more convenient for user  if this is mentioned in guide too.

**Comment by foxmask** [comment]
Yes sure. Thé project is new. Many things need to be done;)
