### ISSUE TITLE
Images not rendered

### ISSUE THREAD

**Issue by foxmask** [foxmask/joplin-web#14]
The web apps is not rendering the images resources and displays

```
!|image name](:/resource_id)
```

**Comment by foxmask** [comment]
fixed by 83d4e3d0a57674af0bc334582b4202851cc2b20f

**Comment by laurent22** [comment]
By the way, if that can be of any help, on Joplin lib there are various Markdown utilities in markdownUtils.js and in Note.replaceResourceInternalToExternalLinks and Note.replaceResourceExternalToInternalLinks

**Comment by foxmask** [comment]
I will make some tests by adding the lib in that vuejs project part . Thanks!
