### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Mohammed90** [foxmask/joplin-web#15]
In your [announcement](https://discourse.joplin.cozic.net/t/joplin-web-a-webapp-for-our-joplin-editor/555), you mentioned you intend to publish a Dockerfile along with the project. This issue is just to keep track of it and serve as a reminder 😄

**Comment by foxmask** [comment]
thanks ;)
I was waiting for a few fixes I made recently. I could try to do it this weekend.

**Comment by kocane** [comment]
@foxmask hey, any news?

**Comment by cferrey** [comment]
@foxmask also very eager to hear of any news on this front!  thanks :)

**Comment by devastar** [comment]
A Docker image would be great, nextcloud editor integration would be even better...

**Comment by foxmask** [comment]
i could do 2 dockers, one for front and one for back but the front does not find the back because of a docker proxy issue i dont know how to handle

**Comment by Mohammed90** [comment]
Can you post the Dockerfiles here? Maybe we can see something or find a solution once we know what we have :)

**Comment by gerroon** [comment]
Yeah Docker image with reverse proxy possibilities would be nice

**Comment by foxmask** [comment]
done 48dc35822250293060736c96ce399c737bd20cc3

**Comment by foxmask** [comment]
@TODO : finding a way to put "--network host" in the `docker-compose.yml`  file

**Comment by Mohammed90** [comment]
Perhaps it's better to use `JOPLIN_PATH` env var in [the docker-compose.yml file](https://github.com/foxmask/joplin-web/blob/040e115fb11c01d22af9c2521ce20b3fdf389c2b/docker-compose.yml#L8) than statically specify the path as it is in your PC.

**Comment by foxmask** [comment]
Yes but here, for the typical use case of `--network host` docker-compose.yml does not work

**Comment by Mohammed90** [comment]
Oh, my comment wasn't in regards to the network thing.

**Comment by cferrey** [comment]
@foxmask any chance you can put this up on Docker Hub so it can be loaded via docker-compose?

**Comment by gerroon** [comment]
Hi

I cloned the repo then

`docker build -t joplin-web-build  .`

after that I do

`docker run -p 8001:8001 joplin-web-build`

which gives an error 

python: can't open file 'app.py': [Errno 2] No such file or directory`

Any recommendations?

**Comment by foxmask** [comment]
I'm on it ; but at first glance I saw the path is wrong:

`Dockerfile` should look like this 

```
FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR  /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY joplin_web /app

EXPOSE 8001
CMD ["python", "/app/app.py"]
```
and `docker-compose.yml` 
```
version: '3.2'
services:
  web:
    build: .
    command: python /app/app.py
    ports:
      - "8001:8001"
```

**Comment by foxmask** [comment]
it should be better with 
```
 docker run -p 8001:8001 joplin-web-build -v JOPLIN_RESOURCES=/path/to/.config/joplin-desktop/resources/ 
```
