### ISSUE TITLE
Email forwarding

### ISSUE THREAD

**Issue by zdog234** [foxmask/joplin-web#20]
Hello! I think it could be interesting to try to implement an email forwarding capability for joplin (similar to how, in evernote/onenote, you can send an email to a personalized email address to save it to a notebook).

It seems like it might make sense to add to this project. When you get a chance, please let me know if you'd rather I create a separate project, or try to structure it as a plugin, so that you don't have to maintain it.

Thanks for the awesome project 🙂

**Comment by foxmask** [comment]
Hi,

Someone already did that as you can see in the app forum of joplin here  [email to joplin gateway](https://discourse.joplinapp.org/t/email-to-joplin-gateway/1336)

Let me know if that covers your needs.
