### ISSUE TITLE
Sorting notes

### ISSUE THREAD

**Issue by foxmask** [foxmask/joplin-web#33]
by 

* title
* date creation
* modification date
* due date

ordered asc/desc

**Comment by nohjlau** [comment]
Hey, I'm interested in tackling this issue.

**Comment by foxmask** [comment]
If you want, as I use bootstrap Vue, the table component manage this feature. You can have a look at it.

https://bootstrap-vue.js.org/docs/components/table

**Comment by nohjlau** [comment]
Nope, I want to implement this feature. I'm a new developer and this seemed like it'd be a good place to start. I created a function and now just need to integrate it into the UI. I don't know if vue has a built-in sort method, so I'll look into the bootstrap link you provided before continuing with my train of thought.

**Comment by foxmask** [comment]
Yes sorry :) with bootstrap Vue that was easy
