### ISSUE TITLE
Multi-language Text/Folder search in single note-taking

### ISSUE THREAD

**Issue by prog20901** [foxmask/joplin-web#40]
Assume the user have 2,000 files of Mark Down in each language...Assume he wants to do the following

a) Choose language
b) Import the MD files

Currently we can import MD files,..However search would happen in all the MD files..

Indexing and Searching should happen per language...So that we can make it as Multi-language and performance will be improved on each language...and search would return only the text of that language.

**Comment by foxmask** [comment]
Hi 
The project is just a cosmetic way to access your Joplin data and does not improve what is alreadyhandled by the core of joplin itself, which in that case is already covered.
