### ISSUE TITLE
Joplin headless from Docker

### ISSUE THREAD

**Issue by tscibilia** [foxmask/joplin-web#41]
Hey, I was doing my best to follow the [readme](https://github.com/foxmask/joplin-web#running) and the [docker readme](https://github.com/foxmask/joplin-web/blob/master/docker.md#docker) as I'm trying to use joplin completely in from a docker container.

I'm currently getting the same HTTP 500 errors that were documented in issue #23
[You replied](https://github.com/foxmask/joplin-web/issues/23#issuecomment-529368179) with a way to start joplin headless but I'm not following how this is achieved within a docker. Do you have any further clarification? is this possible?

**Comment by foxmask** [comment]
Hi,
I've never explained how to run joplin in docker, if this is the thing that disturb you.
I explained to run docker and joplin-web.
joplin-web uses the [https://github.com/foxmask/joplin-api/](joplin-api) which uses by default 127.0.0.1 and the precious webclipper 41148 [here](https://github.com/foxmask/joplin-api/blob/master/joplin_api/core.py#L47-L48)
So once docker is running, and joplin headless by ` joplin start server`, you should make everything work
Hope this can help, just tell me.

**Comment by tscibilia** [comment]
Thanks for the explanation but it's a bit over my head. I'm use to git cloning a repo and modifying an environment file, maybe adding a production or override docker-compose file and doing a simple docker run. 

I was hoping joplin could be run just as simply but I'm not following all the components involved and why they couldn't be part of a simpler docker-compose file. I don't expect a tutorial, you can close this issue at your convenience.

**Comment by foxmask** [comment]
Joplin and joplin-web are 2 differents project, if you want to use docker for Joplin too, you need to ask it to joplin project.
I cant manage that
