### ISSUE TITLE
Official Docker Hub Image with Environment Variable Support

### ISSUE THREAD

**Issue by xianx** [foxmask/joplin-web#45]
Please release a official docker hub image with environment variable support.

**Comment by phil-hudson** [comment]
+1 - any movement?

**Comment by Balooforever** [comment]
+1 :)

**Comment by zxylly1125** [comment]
+1

**Comment by maltokyo** [comment]
+1

**Comment by foxmask** [comment]
I don't plan to support docker ; if you need docker feel free to build your own .
