### ISSUE TITLE
Using Nexcloud as joplin-web Resource

### ISSUE THREAD

**Issue by xianx** [foxmask/joplin-web#46]
We are using Nextcloud and syncying with Joplin Desktop. How can we use Nextcloud as resource in joplin-web?

**Comment by foxmask** [comment]
Hi,
Joplin-web use joplin as a data provider. So the resources you can use from joplin-web with Nextcloud are the same with Joplin.

**Comment by foxmask** [comment]
I think that now you can find what you expect with this new project 
https://discourse.joplinapp.org/t/joplin-web-api-for-nextcloud/4491

**Comment by xianx** [comment]
@foxmask How to use it? No documentation found.
