### ISSUE TITLE
Resetting View does not update the shown filter

### ISSUE THREAD

**Issue by archont00** [foxmask/joplin-web#47]
## Steps

1. On a page reload, no Folder nor Tag is preselected, the heading reads "From Folder /" and all notes are shown.
2. When the user clicks on a folder "Foo", ony the corresponding notes are selected and displayed. Also, the heading updates and shows "From Folder / Foo".
3. Clicking on "Home" or "Joplin Web" clears the "From" filter and all notes are displayed again.

## Problem

The heading still shows "From Folder / Foo".

## What I would expect

The heading text resets to "From Folder /".

## Other notes

This similarly applies when Tags are used as a filter.

P.S. The live search is great!

**Comment by foxmask** [comment]
hi, yes i noticed that issue. i'm on it. for the live search, yes itns crazy ;)
