### ISSUE TITLE
Docker: raise KeyError(f"Config '{key}' is missing,

### ISSUE THREAD

**Issue by gerroon** [foxmask/joplin-web#48]
Hi

I am trying to run the Docker version, I followed the document but I am getting the errors below.

```
docker run --network="host" -p 8282:8001 -v JOPLIN_RESOURCES:/media/DRIVE/joplin-desktop/resources joplin-web-build

WARNING: Published ports are discarded when using host network mode
Traceback (most recent call last):
  File "/app/app.py", line 25, in <module>
    main_app.debug = settings('JW_DEBUG')
  File "/usr/local/lib/python3.6/site-packages/starlette/config.py", line 59, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.6/site-packages/starlette/config.py", line 72, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'JW_DEBUG' is missing, and has no default."
```

**Comment by foxmask** [comment]
You can fix it that way: 

line 25 here https://github.com/foxmask/joplin-web/blob/master/joplin_web/app.py#L25 

instead of 
```
main_app.debug = settings('JW_DEBUG')
```
put 
```
main_app.debug = settings('JW_DEBUG', default=False)
```
then rebuild the image and then you could launch `docker run`

I will fix it later (or you can fork and propose a PR ;)

**Comment by covert8** [comment]
@foxmask I was having this issue myself, but when digging just a bit I found env.sample in the joplin_web dir.
@gerroon is it possible that you have not provided your own env file?

**Comment by foxmask** [comment]
yes, except for 

``` 
joplin = JoplinApi(token=settings('JOPLIN_WEBCLIPPER_TOKEN'))
...
Mount('/files', StaticFiles(directory=settings('JOPLIN_RESOURCES'))),
```
because they can't be guess.

6d3c3ab91142eb132649b71d5b28d152bc6c7bc5
