### ISSUE TITLE
Adding base url

### ISSUE THREAD

**Issue by dangerfish96** [foxmask/joplin-web#49]
Would it be possible to add a BASE_URL environment variable, so that the application can be offered on a subdirectory, e.g /joplin/ and not on / ?

**Comment by foxmask** [comment]
I hope this could do the trick

**Comment by dangerfish96** [comment]
It does not work for some reason... After looking around a bit I noticed occurrences of for example „/static/“ in some template files, e.g index.html.
Maybe they need to be changed as well?

**Comment by foxmask** [comment]
it should be better now
