### ISSUE TITLE
couldn't pull foxmask/joplin-web from dockerhub

### ISSUE THREAD

**Issue by toyqiu** [foxmask/joplin-web#50]
couldn't pull foxmask/joplin-web from dockerhub

docker pull foxmask/joplin-web
Using default tag: latest
Error response from daemon: manifest for foxmask/joplin-web:latest not found

**Comment by foxmask** [comment]
nothing has been done to be handle from dockerhub

**Comment by zxylly1125** [comment]
me too ,How can I get Joplin web from dockerhub?

**Comment by foxmask** [comment]
nothing as nothing has been done to be used from docker hub yet

**Comment by foxmask** [comment]
I don't plan to support docker ; if you need docker feel free to build your own .
