### ISSUE TITLE
Joplin Resources Mapped to WebDAV Not Working

### ISSUE THREAD

**Issue by aashish108** [foxmask/joplin-web#51]
Hi! Been trying to run your fine work this via docker-compose on Windows! I ran into an issue. My Joplin resources are mapped to a drive (which is WebDAV). But the below isn't working. Do you know what goes in here so that it works pls?

```JOPLIN_RESOURCES='S:\My Libraries\Joplin```

Cheers!

**Comment by foxmask** [comment]
did you try to define the var like this 
'VAR=C:/Path/To/My/Resource/Folder' 
for example ?
I don't know how docker manage variables, if it's the unix way or windows way

**Comment by foxmask** [comment]
I will try that 

```
docker run --network="host" -p 8001:8001 -v JOPLIN_RESOURCES:'S:\My Libraries\Joplin' joplin-web-build
```

**Comment by foxmask** [comment]
I don't plan to support docker ; if you need docker feel free to build your own .
