### ISSUE TITLE
Consider making a Yunohost app?

### ISSUE THREAD

**Issue by ei8fdb** [foxmask/joplin-web#52]
I've started using Joplin (and replaced Evernote and Notion.so!) as I've managed to get it synch'ing to my self-hosted Nextcloud. I also use Yunohost for self-hosting applications.

Would you consider creating a Joplinweb [Yunohost app](https://yunohost.org/#/packaging_apps)?

I'm afraid it's beyond my capabilities but I'd be very happy to contribute (if I could get some assistance) and test it if you do.

**Comment by foxmask** [comment]
I'm afraid you won't like my answer.
I don't use nextcloud at all and don't plan to make anything for any system of package. I don't have time. I just made docker image and that's all.

**Comment by ei8fdb** [comment]
Ok, thanks. Would you be against someone packaging joplin-web for Yunohost?

**Comment by foxmask** [comment]
no, why not
