### ISSUE TITLE
Fetch Resources with nextcloud joplin-api

### ISSUE THREAD

**Issue by mrchainman** [foxmask/joplin-web#53]
If serverside encryption is used on the nextcloudserver, you need to mount the joplin folder via webdav to use it as a resource. This shouldn't be needed, as the other joplin aps fetch it directly via nextcloud. It would be great to implement it here. 
Clarification: I am willing to help, but I only know python not js, so my help is limited.

**Comment by foxmask** [comment]
I don't know nextcloud at all.
Everything that is provided by joplin should be usable by joplin-api.
If there is stuff encrypted by nextcloud, joplin-(web|api) will not decrypt it at all, as everything is based on the joplin (and its encryption).
Does it reply to your question ?

**Comment by mrchainman** [comment]
Not really. Let me explain. I plan on running this program on my server, so in order to access the files I would need to mount the nextcloud directory that is on the same server over webdav on the same server, in order for decryption to take place. If this program could talk directly to nextcloud, the decryption could be handled that way. Do you know what I mean? Since this is a special case, if you are not interested in implementing it, feel free to close this issue, otherwise I would be glad to help.

**Comment by foxmask** [comment]
Talking to nextcloud directly is out of the scope of the joplin-api which is just a layer to talk to his/her own joplin notes, and not to stuff providing from something else. For that, you need another lib that will deal with the nextcloud storage (i imagine) to uncrypt/crypt stuff of your choice.
I could have been interested in such a project if only I used nextcloud.
sorry to close that issue.
