### ISSUE TITLE
Undefined path in template

### ISSUE THREAD

**Issue by Pipecity** [foxmask/joplin-web#55]
Hi,

I had a problem with setting up jopin-web and running it in Docker. I followed the instructions and I got it to run fairly easy. The problem I ran into was that nothing was shown in the web application except the footer. After debugging the HTTP communication I saw that the path to the static files started with "/undefined/". After tracking the chain I saw that the index.html template includes the path with an initial "/undefined/" path. So you might want to add this to the instructions because I didn't see anything about this.

Keep up the good work otherwise.
Regards,
Linus

**Comment by Pipecity** [comment]
Oh never mind. I saw that you just fixed this.

**Comment by Pipecity** [comment]
Yeah that didn't work. I changed all the paths in the index.html template to only have it set to "static/..." etc. Now works for me.

**Comment by foxmask** [comment]
the index.html is a generated file, build from npm

All of that is explained in the doc https://github.com/foxmask/joplin-web/blob/master/joplin-vue/README.md
