### ISSUE TITLE
Docker: joplin sync is not triggered automatically

### ISSUE THREAD

**Issue by Strubbl** [foxmask/joplin-web#58]
This is a follow-up issue of #57.

Currently when running joplin-web in a container, the sync process is not triggered automatically. Maybe this is only a config issue with the joplin process we start in the container. I am new to joplin and do not know yet.

So up to now, i am triggering the sync process manually like:

`docker run -v /data/joplin:/data joplin-web-build joplin --profile /data sync`

(sync.interval is not changed, so the default value of 300 seconds is set)

**Comment by foxmask** [comment]
this should have been done with your PR https://github.com/foxmask/joplin-web/pull/73
