### ISSUE TITLE
Do not require note body to be filled out

### ISSUE THREAD

**Issue by Strubbl** [foxmask/joplin-web#60]
Currently it is enforced, that the body of a note (besides the title) has to be filled out. I would prefer to have that form field not required.

Is there any specific reason to make this a required field? I already have some notes from mobile where i have an empty body. Technically it should be possible to add notes with no body content.

**Comment by foxmask** [comment]
may be the Joplin API changed when I started the project and now. I am going to check it

**Comment by Strubbl** [comment]
Thank you :+1:
