### ISSUE TITLE
Can't create folders and tags with docker  in VPS

### ISSUE THREAD

**Issue by aldakur** [foxmask/joplin-web#65]
I deployed joplin-web in my personal VPN following this commands

`sudo docker run -p 8001:8001 -v /data/joplin-desktop:/data -v /data/joplin-resources:/data/joplin-resources -e JW_DEBUG="false" -e JOPLIN_WEBCLIPPER_TOKEN="my_token" -e JOPLIN_RESOURCES="/data/joplin-resources" -e JW_FULL_URL="http://my_vps_ip" imageID`

Apparently everything is working but i can't create folders and tag. When I click in New Folder or New Tags button i can write the name but nothing happen.

Thank you.

**Comment by foxmask** [comment]
Hi,

If you check in the database eg
```
sqlite ~/.confg/joplin-desktop/sqlite.database
```
you should be able to find the folder and tag

On my side I could find the folder I created in the list, but the tags list is not refreshed once you entered a name. If you press F5 you should be able to find the tag.

**Comment by aldakur** [comment]
I try with `sqlite database.sqlite` but this is the return:

`Unable to open database "database.sqlite": file is encrypted or is not a database`

**Comment by foxmask** [comment]
the path to the database is false or the database does not exist

what is the result of 
```
ls ~/.config/joplin-desktop/
clipper-pid.txt  database.sqlite  log-autoupdater.txt  log-clipper.txt  log-database.txt  log.txt  resources  templates  tmp
```

**Comment by aldakur** [comment]
Keep in mind that I run docker container with volumes. like this `-v /data/joplin-desktop:/data -v /data/joplin-resources:/data/joplin-resources`

Result of 
`ls /data/joplin-desktop/`

return for me this:
```
database.sqlite   log-autoupdater.txt  log-database.txt  resources
joplin-resources  log-clipper.txt      log.txt           tmp
```

if I execute 

> cat /data/joplin-desktop/database.sqlite

 I can see that there are notes that I created before with MacOS app and transferred to my VPS via SCP

**Comment by foxmask** [comment]
I don't plan to support docker ; if you need docker feel free to build your own .
