### ISSUE TITLE
Docker version: "can't open file '/app/app.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by maltokyo** [foxmask/joplin-web#76]
Hello, I follwed exactly your docker instructions, and when I run: `docker-compose up` I get an error as follows:
```
Recreating joplin_web ... done
Attaching to joplin_web
joplin_web    | python: can't open file '/app/app.py': [Errno 2] No such file or directory
joplin_web exited with code 2
```

Where is the app.py located please?

**Comment by foxmask** [comment]
at the end of the Dockerfile we can see 

`/app/joplin-web/joplin-web/docker-start.sh`

which, at the end does that :
```
export JW_BASE="/app"
cd "${JW_BASE}/joplin-web/joplin-web/joplin_web" \
  && source "../../bin/activate" \
  && python app.py
```
that means the app.py file should be in `"/app/joplin-web/joplin-web/joplin_web"`

I'm trying to reproduce that

**Comment by foxmask** [comment]
do not use `docker-compose up avec docker-compose.yml` is not uptodate (the correct path should be:
```
    command: python /app/joplin-web/joplin-web/joplin_web/app.py
```
`docker-start.sh` allow us to handle 2 things: sync process, and starting the app.

**Comment by foxmask** [comment]
instead of docker-compose up, if you did 
```
docker build -t joplin-web-build .
```
then try 
```
docker run joplin-web-build
```

**Comment by maltokyo** [comment]
My entire stack is docker-compose. So not interested in just docker run.  I'm not sure that should make a difference (?)

**Comment by foxmask** [comment]
The main diff is in docker-compose.yml which does not start the app at all 
If you know python, you may noticed that in the Dockerfile, a virtual environment is bootstraped ; and then run the app from this virtualenv, which is not the case in docker-compose.yml.

**Comment by foxmask** [comment]
```
docker-compose build 
```
should now build `joplin-web_web`  image
then could be started like that:
```
docker run -p 8001:8001 -v /data/joplin-desktop:/data -e JW_FULL_URL="http://192.168.0.1:8001/" joplin-web_web
```

**Comment by maltokyo** [comment]
Now get a different error when I run `docker-compose build`
```
Building joplin_web
Step 1/9 : FROM python:3.8-buster
3.8-buster: Pulling from library/python
Digest: sha256:97acbabcb7ab00f6aedbcb0888621600d3a8a0e1124d0f436d2e63686c34b414
Status: Downloaded newer image for python:3.8-buster
 ---> bbf31371d67d
Step 2/9 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 03036760ef82
Step 3/9 : ENV PYTHONUNBUFFERED=1     JW_FULL_URL="http://127.0.0.1:8001/"     JW_SYNC_SECONDS=300
 ---> Using cache
 ---> c058058616bf
Step 4/9 : WORKDIR /app
 ---> Using cache
 ---> 59e50d659bbf
Step 5/9 : RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -   && apt-get install -y libsecret-1-dev nodejs   && NPM_CONFIG_PREFIX=/joplin-bin npm install --unsafe-perm -g joplin   && ln -s /joplin-bin/bin/joplin /usr/bin/joplin   && export JW_BASE=/app   && cd "${JW_BASE}"   && python3 -m venv joplin-web   && cd joplin-web   && source bin/activate   && git clone https://github.com/foxmask/joplin-web   && cd joplin-web   && pip install -r requirements.txt   && cd joplin-vue   && npm install   && npm run build   && mkdir /data
 ---> Using cache
 ---> 28a3a8219344
Step 6/9 : VOLUME /data
 ---> Using cache
 ---> 343942027ed0
Step 7/9 : EXPOSE 8001
 ---> Using cache
 ---> bed0d8f58bb8
Step 8/9 : COPY joplin_web/.env_docker /app/joplin-web/joplin-web/joplin_web/.env
ERROR: Service 'joplin_web' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder162439494/joplin_web/.env_docker: no such file or directory
```

**Comment by foxmask** [comment]
copy the .env file into .env_docker and set the path to the data resources folder
I'll paste mine if you don't get it

**Comment by maltokyo** [comment]
Please paste. I can't get it working...

**Comment by foxmask** [comment]
ok but not today.

**Comment by foxmask** [comment]
my `joplin_web/.env` file looks like that

```
11:33 $ more joplin_web/.env
# running in debug mode or not ?
JW_DEBUG = False
# number of notes to get for each page
JW_PAGINATOR = 20
# listen port number
JW_HTTP_PORT = 8001
# the token ID you grab from the WebClipper config page with your Joplin
JOPLIN_WEBCLIPPER_TOKEN = 'the token'
# path to get the joplin `resources` to be able to display them
JOPLIN_RESOURCES = '/home/foxmask/.config/joplin-desktop/resources/'
# BASE URL of the Joplin APP
JW_BASE_URL = '/'
```

and my `joplin_web/.env_docker` file looks like that

```
✔ ~/Projects/joplin-web/joplin-web [master|…3⚑ 1] 
11:32 $ more joplin_web/.env_docker 

# running in debug mode or not ?
JW_DEBUG = False
# number of notes to get for each page
JW_PAGINATOR = 20
# listen port number
JW_HTTP_PORT = 8001
# the token ID you grab from the WebClipper config page with your Joplin
JOPLIN_WEBCLIPPER_TOKEN = 'the token'
# path to get the joplin `resources` to be able to display them
JOPLIN_RESOURCES = '/data/resources/'
# BASE URL of the Joplin APP
JW_BASE_URL = '/'
```
have [a look at the operations to do before running docker-compose](https://github.com/foxmask/joplin-web/blob/master/docker.md)

**Comment by archont00** [comment]
Still, it is unclear why your docker-compose.yml keeps the `command: python /app/app.py` line.

During the container start it effectively replaces the `CMD ["/app/joplin-web/joplin-web/docker-start.sh"]` in Dockerfile, which means that a) joplin client and interval sync are not run and b) bootstrapping for python does not happen and eventually the /app/app.py fails. 

P.S. The docker-compose.yml also lacks the `volumes:` section to mount the host's joplin profile dir into the container.

**Comment by foxmask** [comment]
then, if you know how to fix that, feel free to submit a PR, as I don't know how to.

**Comment by archont00** [comment]
I will do so later this week - see also #78 where I included a full docker-compose.yml (without modifying your Dockerfile) in the meantime.
