### ISSUE TITLE
JW_FULL_URL in docker-compose (working docker-compose.yml included)

### ISSUE THREAD

**Issue by archont00** [foxmask/joplin-web#78]
I was not able to figure out what the JW_FULL_URL should be - the web app did not load. 
And have eventually set it to "/" only, which seems to work without problems.

My setup:
- docker-compose running the image (built from this project's Dockerfile) on localhost.
- limited access to the mapped port only from localhost
- nxing ssl proxy with user authentication on localhost re-directing all external calls to https://joplin.example.org to localhost:port of the container.

This is the working `docker-compose.yml`:
```
# If need be - updating image and container:
#   docker-compose down # Removes everything but persistent volumes
#   docker-compose build --no-cache --pull --force-rm # Rebuilds local Dockerfile
#   docker-compose up -d   # Starts container

version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: joplinweb:latest
    container_name: joplinweb
    ports:
      # On your docker host, point your browser or web proxy to http://localhost:7101 to access Joplin Web
      - 127.0.0.1:7101:8001
    volumes:
      # The first parameter is existing path on docker host to a copy of Joplin Desktop profile dir
      # docker runs on a headless server, so the profile dir is a copy from my desktop computer
      - /var/lib/docker-vol/joplin_profile:/data
    environment:
      - JW_DEBUG=False
      - JW_PAGINATOR=20
      - JW_BASE_URL=/  # With trailing slash
      - JW_FULL_URL=/
      - JW_HTTP_PORT=8001
      # See Joplin Desktop App:
      # // Tools // Web clipper options: Authorization token
      - JOPLIN_WEBCLIPPER_TOKEN=blablatoken
      - JOPLIN_RESOURCES=/data/resources/
    restart: "unless-stopped"
    #command: /app/app.py # this cannot work - the file does not exist
    #command: /bin/sh -c 'export; while true; do echo "Staying Alive!"; sleep 60; done'
```
There are `.env_docker`, `Dockerfile` and this `docker-compose.yml` in docker directory only. `.env_docker` is empty (required by `Dockerfile`, however I prefer setting up variables via `docker-compose.yml`).

Feel free to re-use some parts to update your `docker-compose.yml`.

**Comment by foxmask** [comment]
this in the url from which the application will be available
for example
```
docker run -p 8001:8001 -v /data/joplin-desktop:/data -e JW_FULL_URL="http://192.168.0.3:8001/" joplin-web-build
```

**Comment by archont00** [comment]
Yeah, I know. But it is unclear to me:
- Is there any problem if JW_FULL_URL="/"? Seems to work in docker for me (tested only briefly).
- If it is okay, why would anyone want to set it to full IP address?
- How about accessing the Joplin Web from LAN and from WAN? From user's perspective, these are different IP addresses.
- Or can it be FQDN like http://joplin.example.org?

**Comment by foxmask** [comment]
If I remember the user who requested me that, that was to be able to start docker on a VM at Hosting provider and accessing Joplin from there.
But you are right with only JW_FULL_URL="/" it should be enough, and a proxy should do the trick.
